### ISSUE TITLE
When creating a new ATProto account, handle existing DNS record

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1072]
Right now, when we create a new ATProto repo and DID, if our `_atproto` DNS record for handle resolution already exists, we crash. We should handle that and recover instead. Example log below; exception is [`google.api_core.exceptions.Conflict`](https://googleapis.dev/python/google-api-core/latest/exceptions.html#google.api_core.exceptions.Conflict). [Docs don't help much.](https://cloud.google.com/dns/docs/error-messages#alreadyexists) [Haven't](https://cloud.google.com/s/results?q=dns+overwrite&text=dns+overwrite) [found](https://cloud.google.com/s/results?q=dns+overwrite&text=dns+replace) a way to tell it to overwrite/replace existing records, so I may need to either catch the exception or look up the record first. cc @gabboman

```
adding GCP DNS TXT record for _atproto.gabboman.app.wafrn.net.ap.brid.gy. "did=did:plc:qh4q7p2njfcpbwjxswox7bcy"
<class 'google.api_core.exceptions.Conflict'>: 409 POST https://dns.googleapis.com/dns/v1/projects/brid-gy/managedZones/brid-gy/changes?prettyPrint=false: The resource 'entity.change.additions[_atproto.gabboman.app.wafrn.net.ap.brid.gy.][TXT]' named '_atproto.gabboman.app.wafrn.net.ap.brid.gy. (TXT)' already exists
Traceback (most recent call last):
...
  File "workspace/protocol.py", line 1501, in receive_task
    return PROTOCOLS[obj.source_protocol].receive(obj=obj, authed_as=authed_as,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "workspace/protocol.py", line 930, in receive
    from_user.enable_protocol(proto)
...
  File "workspace/models.py", line 467, in enable_protocol
    enable()
  File "workspace/atproto.py", line 352, in create_for
    changes.create()
  File "google/cloud/dns/changes.py", line 233, in create
    api_response = client._connection.api_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Conflict: 409 POST https://dns.googleapis.com/dns/v1/projects/brid-gy/managedZones/brid-gy/changes?prettyPrint=false: The resource 'entity.change.additions[_atproto.gabboman.app.wafrn.net.ap.brid.gy.][TXT]' named '_atproto.gabboman.app.wafrn.net.ap.brid.gy. (TXT)' already exists
```

**Comment by snarfed** [comment]
We still see a steady trickle of these, roughly one a day on average: https://console.cloud.google.com/errors/detail/COibqNv9r7ynFg;filter=%5B%5D;time=P30D?project=bridgy-federated

**Comment by snarfed** [comment]
I wonder if #1063 will mostly or entirely prevent this.

**Comment by snarfed** [comment]
Nope, we're still seeing a trickle.

**Comment by snarfed** [comment]
Done! And I fixed (I think) pretty much everyone who hit this in the last 30d or so.
