### ISSUE TITLE
atproto_firehose subscriber falls behind when atproto-hub is busy

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1641]
Started seeing an ugly failure mode in atproto-hub yesterday: our firehose consumer slowed down below the Bluesky relay's event rate, so we started falling behind. atproto-hub is CPU bound, and we had many (8-10) other firehose clients consuming our firehose at the same time, which is high. I dropped `ROLLBACK_WINDOW` from 200k seqs to 50k, and added a second core to atproto-hub, which seemed to help, but we were still falling behind occasionally for a bit and then catching back up. odd.

<img width="290" alt="image" src="https://github.com/user-attachments/assets/d0a28b24-66c6-4295-9a26-ec17377c3e89" />

<img width="290" alt="image" src="https://github.com/user-attachments/assets/386f8c7c-21c4-4109-8b1e-8ee388c23fa0" />

...and then this morning it got worse. I added snarfed/lexrpc@22d9fee6ea1c85623987f05f997902e942ecc139 to shed load by denying additional connections from the same IP after the first, which helped, so we're now out of the woods:

<img width="290" alt="image" src="https://github.com/user-attachments/assets/f4f9ae68-b34e-4702-adc1-a9edd85dcdbb" />
<img width="290" alt="image" src="https://github.com/user-attachments/assets/2274c6e2-744b-476a-9814-ad768a3a7cde" />

I still don't fully understand the failure mode though.

**Comment by snarfed** [comment]
Saw this again just now. 😕

**Comment by snarfed** [comment]
The original cause here was lots (for us) of subscribers, but another more acute cause (I think) is when subscribers connect with an older cursor. Our current rollback window of 50k seqs limits this, but this still regulary blocks our handling new commits from the relay's firehose pretty regularly.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/f6d0b849-4d66-46c1-b5b3-fbd48f78e12b" />
<br>
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/7db61215-2d8e-4fac-b21a-2866ec3418ab" />

**Comment by snarfed** [comment]
Damn, didn't fix it.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/029ae9c1-20e4-4c93-b83c-bbbce4566ae4" />
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/11d859b2-c307-45e2-8d43-1d8cbeeaa144" />

**Comment by snarfed** [comment]
Root cause here is that the worker itself is flapping. Not sure why yet.

**Comment by snarfed** [comment]
Bumped the gunicorn timeout up to 5m, interesting result, the worker kept flapping, but only at 5m intervals, so it got a chance to do some work between flaps. Next step is to disable the timeout altogether.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/5046d7fd-5375-49d1-a339-b08a737387f0" />
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/fcc8663b-6671-41a7-8496-45c199d9c4d4" />

**Comment by snarfed** [comment]
No timeout made our firehose consumer happy, but our firehose _server_ died after ~90m. Grr.

<img width="577" alt="Image" src="https://github.com/user-attachments/assets/218e281d-af14-492c-b916-d44be82377b1" />

**Comment by snarfed** [comment]
0 timeout and allowing duplicate connections definitely didn't work, still need to look into what exactly happened.symptoms.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/b982434f-de9b-4235-bc00-226a362a0f59" />
<br>
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/825ae6b9-8c71-4dfb-b40e-7d88e37d790e" />

**Comment by snarfed** [comment]
Looks like this isn't a bug per se, it's just that serving from our rollback window is expensive and inefficient right now due to https://github.com/snarfed/arroba/issues/30 , and a single client, 152.53.36.179, keeps reconnecting with a 2.5d-old sequence #, 14675627, which is far behind our rollback window, and they keep reconnecting with it every hour.

(We currently do ~100k seqs/d, so our current 50k rollback window is ~12h.)

**Comment by snarfed** [comment]
Interestingly this has no meaningful impact on our datastore load:

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/1870e4be-bfd0-4d6b-a70f-04b402361c54" />
<br>
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/4cc2c040-4059-4745-bb4f-9d68dfae21fb" />

**Comment by snarfed** [comment]
152.53.36.179 is a pretty aggressive client, they try to open lots of duplicate connections, [re]connecting every 1-5m or so while still holding existing connections open. 😕

**Comment by snarfed** [comment]
Blocked them, at least temporarily. I'd love to allow them again as soon as they stop constantly reloading the rollback window.

Otherwise, timeout 0 seems to have done the trick here!

**Comment by snarfed** [comment]
Good progress here btw! Not seeing the ATProto firehose consume side delays any more.

<img width="578" alt="Image" src="https://github.com/user-attachments/assets/f09abd2b-2c46-41ec-9144-5d0256993865" />

**Comment by snarfed** [comment]
Reopening, ugh, saw https://github.com/snarfed/bridgy-fed/issues/1641#issuecomment-2766629640 again, firehose consumer died roughly ~1h after a deploy.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/affc1d6f-6cd9-4af8-8392-a7900634bf15" />
<br>
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/89ccf6f9-f13a-44aa-bffd-85943cb1a43e" />

**Comment by snarfed** [comment]
Looks like this is a gunicorn sync worker (gthread) worker crash. Seems like it takes out the main thread, but the rest of the worker, ie the open websocket connections, keeps going, so it doesn't restart? Logs:

```
Traceback (most recent call last):
  File ".../python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File ".../python3.12/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File ".../python3.12/site-packages/gunicorn/workers/base.py", line 143, in init_process
    self.run()
  File ".../python3.12/site-packages/gunicorn/workers/gthread.py", line 213, in run
    callback(key.fileobj)
  File ".../python3.12/site-packages/gunicorn/workers/gthread.py", line 128, in accept
    self.poller.register(conn.sock, selectors.EVENT_READ,
  File ".../python3.12/selectors.py", line 352, in register
    key = super().register(fileobj, events, data)
Rejecting connection, already connected for com.atproto.sync.subscribeRepos: 38.120.64.66 Go-http-client/1.1
...
  File ".../python3.12/selectors.py", line 241, in register
    raise KeyError("{!r} (FD {}) is already registered"
KeyError: "<socket.socket fd=20, family=2, type=1, proto=0, laddr=('172.17.0.5', 8080), raddr=('172.17.0.4', 15006)> (FD 20) is already registered"
[2025-04-02 22:39:23 +0000] [9] [INFO] Worker exiting (pid: 9)
[error] 34#34: *3605 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.253.122.121, server: , request: "GET /xrpc/com.atproto.sync.subscribeRepos?cursor=15019381 HTTP/1.1", upstream: "http://172.17.0.1:8080/xrpc/com.atproto.sync.subscribeRepos?cursor=15019381", host: "atproto.brid.gy"
```

Related:
* https://github.com/benoitc/gunicorn/issues/1258
* https://github.com/GoogleCloudPlatform/python-compat-runtime/issues/94
* https://stackoverflow.com/questions/26634327/gunicorn-worker-periodically-crashes-socket-is-not-registered

**Comment by snarfed** [comment]
The other thing I'm thinking about is, since websocket connections are long lived, ideally we'd mark them as daemons so that they wouldn't block the worker itself from quitting and restarting?

**Comment by snarfed** [comment]
Same thing happened a bit ago, different stack trace but same ultimate effect, worker quit but maybe the open websocket connections kept it around?

```
[2025-04-02 23:58:31 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
    super().init_process()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/base.py", line 143, in init_process
    self.run()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 213, in run
    callback(key.fileobj)
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 149, in on_client_socket_readable
    self.enqueue_req(conn)
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 114, in enqueue_req
    conn.init()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 50, in init
    self.sock.setblocking(True)
OSError: [Errno 9] Bad file descriptor
[2025-04-02 23:58:31 +0000] [9] [INFO] Worker exiting (pid: 9)
```

**Comment by snarfed** [comment]
A bigger hammer here would be migrating to Cloud Run. I have no concrete reason to think that would fix this, and it'd take work, and I'm sure we'd hit entirely new issues...but 🤷

**Comment by snarfed** [comment]
Really feeling confused here. atproto-hub regularly sees worker failures like the ones above, but gunicorn does contain them somehow. However, seeing atproto-commit tasks back up and https://fed.brid.gy/admin/atproto requests hang indefinitely makes me think we're leaking gunicorn request handler threads. Not good...especially since if there are still some active websocket clients, the worker will stay alive, even if it's out of threads and new clients aren't able to connect. Grr.

Trying a big thread pool, `--threads 1000`, just to mitigate this a bit.

**Comment by snarfed** [comment]
Seems like `--threads 1000` did the trick! 🤷
