### ISSUE TITLE
Unfollow bug

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#402]
when `last_follow.object` is a string, not an object? eg @snarfed.org@snarfed.org => @spolsky@blackrock.city. https://console.cloud.google.com/errors/detail/CIHQk8v61sGIYA;time=P30D?project=bridgy-federated

```
Traceback (most recent call last):
...
  File "/Users/ryan/src/oauth-dropins/oauth_dropins/indieauth.py", line 224, in dispatch_request
    return self.finish(indie_auth, state=state)
  File "/Users/ryan/src/bridgy-fed/follow.py", line 209, in finish
    inbox = last_follow['object']['inbox']
TypeError: string indices must be integers
```

**Comment by snarfed** [comment]
Fixed in https://github.com/snarfed/oauth-dropins/pull/286, moved on to a BF bug: https://console.cloud.google.com/errors/detail/CIHQk8v61sGIYA;time=P30D?project=bridgy-federated

```
ypeError: string indices must be integers
at .finish ( /workspace/follow.py:209 )
at .dispatch_request ( /layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/indieauth.py:224 )
at .handle_exception ( /layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/flask_util.py:208 )
```
