### ISSUE TITLE
Error handling for `Object`s that fail because they're too big

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#636]
Started seeing [this error](https://console.cloud.google.com/errors/detail/CO-fpZfMq_6ktgE;time=P30D?project=bridgy-federated) yesterday on https://maurice-renck.de/de/blog/2023/podcaster-plugin-3 ([parsed mf2](https://pin13.net/mf2/?url=https://maurice-renck.de/de/blog/2023/podcaster-plugin-3)), which includes a big inlined `data:` img. Datastore raised ` google.api_core.exceptions.InvalidArgument: 400 entity is too big`, which we don't yet handle, so we 500ed.

[Datastore max property value size and entity size](https://cloud.google.com/datastore/docs/concepts/limits) are both 1MB. OK. Total parsed mf2 size is only 200KB though, and the converted `as1` computed property is similarly ~200KB. So why does the datastore think we're over 1MB?

...arguably it doesn't matter, we should just handle this exception and return HTTP 400.

**Comment by snarfed** [comment]
#1501 is probably the most common cause of this, doing that should help.

**Comment by snarfed** [comment]
Did #1501, haven't seen this in the last 30d. Tentatively closing.

**Comment by snarfed** [comment]
Still seeing this, eg on some web pages, eg `Web.load('https://numagasablog.com/entry/2025/12/31/170921')` triggers it:

```
Traceback (most recent call last):
  File "/Users/ryan/src/bridgy-fed/web.py", line 539, in load
    return super().load(id, **kwargs)
  File "/Users/ryan/src/bridgy-fed/protocol.py", line 2095, in load
    obj.source_protocol = cls.LABEL
  File "/Users/ryan/src/oauth-dropins/oauth_dropins/webutil/models.py", line 31, in put
    return super(StringIdModel, self).put(*args, **kwargs)
...
  File "/Users/ryan/src/bridgy-fed/local/lib/python3.12/site-packages/google/cloud/ndb/_datastore_api.py", line 102, in rpc_call
    raise error
google.api_core.exceptions.InvalidArgument: 400 entity is too big
```
