### ISSUE TITLE
ActivityPub => ATProto profile update

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#960]
Currently crashing when we try to write the UPDATE of the `app.bsky.actor.profile` record:

```
Sending https://indieweb.social/users/snarfed#updates/1713224298 AS1: {
  "objectType": "activity",
  "verb": "update",
  "id": "https://indieweb.social/users/snarfed#updates/1713224298",
  "actor": {
    "id": "https://indieweb.social/users/snarfed",
    ...
  },
  "to": [
    {"id": "https://www.w3.org/ns/activitystreams#Public"},
    { "objectType": "group", "alias": "@public"}
  ],
  "object": {
    "objectType": "person",
    "id": "https://indieweb.social/users/snarfed",
    "summary": "<p>Follow me on the fediverse at <span class=\"h-card\" translate=\"no\"><a href=\"https://fed.brid.gy/r/https://snarfed.org/\" class=\"u-url mention\">@<span>snarfed.org</span></a></span>! This account is just for DMs, testing, etc.</p>",
    "url": "https://indieweb.social/@snarfed",
    "endpoints": {"sharedInbox": "https://indieweb.social/inbox"},
    "displayName": "Ryan Barrett",
    "username": "snarfed",
    "image": [{
        "url": "https://cdn.masto.host/indiewebsocial/accounts/avatars/109/130/869/961/539/408/original/6a96256645c6c1f4.png",
        "mimeType": "image/png",
        "objectType": "image"
      }]
    ...
  }
}

Key('ActivityPub', 'https://indieweb.social/users/snarfed') is did:plc:bg5udl25mvzg3rt7l5n2hzet
Loading repo Key('AtpRepo', 'did:plc:bg5udl25mvzg3rt7l5n2hzet')
loaded repo for did:plc:bg5udl25mvzg3rt7l5n2hzet at commit bafyreiej2bzgcekxb33r36wuwvs72eefoa4p7iaxhjsyxfenl36omypod4

Traceback (most recent call last):
  File "/workspace/protocol.py", line 1287, in send_task
    sent = PROTOCOLS[protocol].send(obj, url, from_user=user, orig_obj=orig_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/atproto.py", line 407, in send
    write()
  File "/workspace/atproto.py", line 396, in write
    assert copy_did == did
           ^^^^^^^^^^^^^^^
AssertionError: ('did:plc:3lykmzdk3ielokeonpl5tb72', 'did:plc:bg5udl25mvzg3rt7l5n2hzet')
```

**Comment by snarfed** [comment]
Still happening!

**Comment by snarfed** [comment]
I think this was an artifact of bad data in this account specifically, since I created it so early in development. Waiting for caches to expire to confimr.
